BI-463-Disable-TeamCity-Size-checker-when-not-merging-master
lip/commit-status-publisher pull request #6
Opened 2017-07-13 02:24 UTC by manhtran1609

2017-07-13 16:33 UTC, lip requested changes
Looks solid and we just need some minor clean up on it

2017-07-13 16:33 UTC, lip commented on commit-status-publisher-server/src/main/java/jetbrains/buildServer/commitPublisher/github/ChangeStatusUpdater.java
> +                }
If the branches don't match we should do another comment.append("Not merging into master, not calculating artifact size\n") or something like that

2017-07-13 16:33 UTC, lip commented on commit-status-publisher-server/src/main/java/jetbrains/buildServer/commitPublisher/github/ChangeStatusUpdater.java
> +              LOG.warn("Failed to find base branch for " + version.getVcsBranch() + " for repository " + repositoryName);
Please add this information into the comment field so when this happens it will be caught easily

2017-07-13 16:33 UTC, lip commented on commit-status-publisher-server/src/main/java/jetbrains/buildServer/commitPublisher/github/api/GitHubApi.java
> +                               @NotNull String branchName) throws IOException;
Minor but please line up the @NotNull vertically so it's easier to read

2017-07-13 16:33 UTC, lip commented on commit-status-publisher-server/src/main/java/jetbrains/buildServer/commitPublisher/github/api/impl/GitHubApiImpl.java
> +                                      @NotNull String branchName) throws IOException {
Minor but please line up the @NotNull vertically so it's easier to read

2017-07-14 08:20 UTC, manhtran1609 commented
thanks @lip , I updated as your suggestion.

2017-07-17 23:54 UTC, lip approved these changes

2017-07-17 23:54 UTC, merged